"use client";

import { useFormulaBuilderDerivedState } from "./formula-builder-derived";
import { useFormulaBuilderCatalogState } from "./formula-builder-catalog";
import { useFormulaLineActions } from "./formula-builder-line-actions";
import { useFormulaBuilderUiState } from "./formula-builder-ui-state";
import { useExcelImportState } from "./excel-import-state";
import {
  useSavedFormulaComparisonDerivedState,
  useSavedFormulaComparisonState,
} from "./saved-formula-comparison-state";
import { useSavedFormulaActions } from "./saved-formula-actions";
import { useJiraReviewActions } from "./jira-review-actions";
import { useExcelImportActions } from "./excel-import-actions";
import { useJiraConnectionActions } from "./jira-connection-actions";
import { useAiAssistantActions } from "./ai-assistant-actions";
import { useCompatibilityActions } from "./compatibility-actions";
import { useRawMaterialActions } from "./raw-material-actions";
import { useWorkspaceSettingsActions } from "./workspace-settings-actions";
import { useDraftReviewActions } from "./draft-review-actions";
import { useFormulaBuilderLocalActions } from "./formula-builder-local-actions";
import {
  useAuthenticatedWorkspaceLoad,
  useWorkspaceAuthSession,
} from "./workspace-auth-session";
import { useWorkspaceCapabilities } from "./workspace-capabilities";
import { useWorkspaceCoreState } from "./workspace-core-state";
import { useRawMaterialWorkspaceState } from "./raw-material-state";
import { useFormulaWorkspaceState } from "./formula-workspace-state";
import { useCompatibilityState } from "./compatibility-state";
import { useAiWorkflowState } from "./ai-workflow-state";
import { useJiraConnectionState } from "./jira-connection-state";
import { WorkspaceAuthGate } from "./workspace-auth-gate";
import { WorkspaceHomeView, type WorkspaceHomePanels } from "./workspace-home-view";
import { useWorkspaceShellState } from "./workspace-shell-state";

export function WorkspaceHome() {
  const {
    workspace,
    setWorkspace,
    workspaceName,
    setWorkspaceName,
    parameterForm,
    setParameterForm,
    tenantInvitations,
    setTenantInvitations,
    invitationForm,
    setInvitationForm,
  } = useWorkspaceCoreState();
  const {
    materialForm,
    setMaterialForm,
    detailedMaterialIds,
    setDetailedMaterialIds,
    aliasInputs,
    setAliasInputs,
    resetRawMaterialWorkspaceState,
  } = useRawMaterialWorkspaceState();
  const {
    formulaMaterialQuery,
    parameterViewPreset,
    customParameterCodes,
    showOnlyPositiveParameters,
    catalogFamilyFilter,
    catalogPriceFilter,
    catalogPriceMin,
    catalogPriceMax,
    catalogParameterToAdd,
    catalogParameterConditions,
    materialResultLimit,
    selectedMaterialId,
    comparisonMaterialIds,
    expandedMaterialIds,
    builderSections,
    setFormulaMaterialQuery,
    setShowOnlyPositiveParameters,
    setCatalogFamilyFilter,
    setCatalogPriceFilter,
    setCatalogPriceMin,
    setCatalogPriceMax,
    setCatalogParameterToAdd,
    setMaterialResultLimit,
    setSelectedMaterialId,
    setComparisonMaterialIds,
    setExpandedMaterialIds,
    setBuilderSections,
    resetFormulaBuilderSelection,
    selectParameterView,
    toggleCustomParameterCode,
    addCatalogParameterCondition,
    updateCatalogParameterCondition,
    removeCatalogParameterCondition,
    resetCatalogFilters,
    toggleBuilderSection,
  } = useFormulaBuilderUiState();
  const {
    result,
    setResult,
    formulas,
    setFormulas,
    calculationHistory,
    setCalculationHistory,
    formulaReviewRequests,
    setFormulaReviewRequests,
    formulaReviewArtifacts,
    setFormulaReviewArtifacts,
    resetFormulaWorkspaceState,
  } = useFormulaWorkspaceState();
  const {
    compatibilityRules,
    setCompatibilityRules,
    compatibilityRuleForm,
    setCompatibilityRuleForm,
    resetCompatibilityState,
  } = useCompatibilityState();
  const {
    jiraConnections,
    setJiraConnections,
    jiraConnectionForm,
    setJiraConnectionForm,
    jiraMetadata,
    setJiraMetadata,
    jiraMappingKey,
    setJiraMappingKey,
    resetJiraConnectionState,
  } = useJiraConnectionState();
  const {
    requirementText,
    setRequirementText,
    requirementParse,
    setRequirementParse,
    agentPlan,
    setAgentPlan,
    draftReview,
    setDraftReview,
    aiRuns,
    setAiRuns,
    resetAiWorkflowState,
  } = useAiWorkflowState();
  const {
    formulaCompareSelection,
    comparisonConstraintForm,
    showOnlyConstraintIssues,
    savedFormulaComparison,
    selectFormulaForComparison,
    updateComparisonConstraint,
    resetSavedFormulaComparisonState,
    setShowOnlyConstraintIssues,
    setSavedFormulaComparison,
  } = useSavedFormulaComparisonState();
  const {
    importPreview,
    importFile,
    importFileName,
    availableImportSheets,
    selectedImportSheet,
    resetImportState,
    setPendingFile,
    setPreview: setImportPreview,
    setSelectedImportSheet,
    resolveImportRow: resolveImportRowState,
  } = useExcelImportState();
  const { activeView, setActiveView, status, message, setStatus, setMessage, setError, runAction } =
    useWorkspaceShellState();
  const { session, authChecked, authHeaders, headers, uploadHeaders } =
    useWorkspaceAuthSession(workspace.tenant);
  const {
    catalogMaterialIds,
    catalogTotal,
    catalogFamilies,
    catalogLoading,
    refreshCatalog,
  } = useFormulaBuilderCatalogState({
    enabled: Boolean(workspace.tenant && session?.access_token),
    headers,
    query: formulaMaterialQuery,
    familyFilter: catalogFamilyFilter,
    priceFilter: catalogPriceFilter,
    priceMin: catalogPriceMin,
    priceMax: catalogPriceMax,
    parameterConditions: catalogParameterConditions,
    materialResultLimit,
    showOnlyPositiveParameters,
    parameterViewPreset,
    setWorkspace,
    setMaterialResultLimit,
    setError,
  });
  const {
    createWorkspace,
    loadAuthenticatedWorkspace,
    signOut,
    createTenantInvitation,
    createParameter,
  } = useWorkspaceSettingsActions({
    workspace,
    workspaceName,
    invitationForm,
    parameterForm,
    authHeaders,
    headers,
    setWorkspace,
    setWorkspaceName,
    setResult,
    setTenantInvitations,
    setStatus,
    setInvitationForm,
    resetFormulaBuilderSelection,
    resetRawMaterialWorkspaceState,
    resetFormulaWorkspaceState,
    resetCompatibilityState,
    resetJiraConnectionState,
    resetAiWorkflowState,
    resetSavedFormulaComparisonState,
    resetImportState,
    updateComparisonConstraint,
    refreshCatalog,
    runAction,
    setError,
    setMessage,
  });

  useAuthenticatedWorkspaceLoad({
    session,
    tenant: workspace.tenant,
    loadAuthenticatedWorkspace,
  });

  const {
    rawMaterialsById,
    formulaLineDetails,
    parameterCatalog,
    visibleParameterCodes,
    visibleParameterCodeSet,
    selectedParameterPreset,
    formulaBasicsValue,
    visibleParameterSummary,
    materialSearchResults,
    selectedMaterial,
    selectedMaterialParameters,
    comparisonMaterials,
    parameterRows,
    catalogMaterialFamilies,
    draftComparison,
    totalPercentage,
    isFormulaBalanced,
    formulaCompositionPrice,
    formulaCompositionPriceSource,
    visibleWarnings,
  } = useFormulaBuilderDerivedState({
    workspace,
    catalogMaterialIds,
    catalogFamilies,
    parameterViewPreset,
    customParameterCodes,
    selectedMaterialId,
    showOnlyPositiveParameters,
    comparisonMaterialIds,
    result,
    draftReview,
  });
  const {
    comparisonMaterialOptions,
    comparisonConstraintEvaluations,
    comparisonComplianceSummary,
    comparisonConstraintIssueCount,
    visibleComparisonConstraintEvaluations,
  } = useSavedFormulaComparisonDerivedState({
    formulas,
    rawMaterials: workspace.rawMaterials,
    formulaCompareSelection,
    comparisonConstraintForm,
    savedFormulaComparison,
    showOnlyConstraintIssues,
  });
  const {
    isBusy,
    canEditTenantData,
    canManageTenantUsers,
    showInvitationAdminPanel,
    hasPendingDraftReview,
    canConfirmDraftReview,
    canSaveFormula,
    canCompareSavedFormulas,
    canSelectImportSheet,
    canSaveImport,
    canParseRequirements,
    canPlanRequirements,
    canCreateCompatibilityRule,
    activeJiraConnection,
    canSaveJiraConnection,
    canTestJiraConnection,
    canLoadJiraMetadata,
    canAuthorizeJiraOAuth,
    canPrepareJiraReview,
    canSearchCatalog,
  } = useWorkspaceCapabilities({
    workspace,
    status,
    draftReview,
    isFormulaBalanced,
    formulaCompareSelection,
    availableImportSheets,
    importFile,
    importPreview,
    requirementText,
    compatibilityRuleForm,
    jiraConnections,
    jiraConnectionForm,
    result,
  });
  const {
    ensureRawMaterialDetail,
    inspectMaterial,
    toggleCompareMaterial,
    toggleExpandedMaterial,
    createMaterial,
    createAlias,
  } = useRawMaterialActions({
    workspace,
    rawMaterialsById,
    detailedMaterialIds,
    materialForm,
    aliasInputs,
    headers,
    setWorkspace,
    setDetailedMaterialIds,
    setSelectedMaterialId,
    setComparisonMaterialIds,
    setExpandedMaterialIds,
    setMaterialForm,
    setAliasInputs,
    setResult,
    refreshCatalog,
    resetImportState,
    runAction,
    setError,
    setMessage,
  });
  const {
    markDraftReviewPending,
    updateDraftReviewNotes,
    confirmDraftReview,
    applyOptimizerDraft,
  } = useDraftReviewActions({
    workspace,
    draftReview,
    agentPlan,
    headers,
    setWorkspace,
    setCalculationHistory,
    setResult,
    setBuilderSections,
    setDraftReview,
    runAction,
    setError,
    setMessage,
  });
  const {
    addFormulaLine,
    removeFormulaLine,
    updateFormulaLine,
    moveFormulaLine,
    duplicateFormulaLine,
  } = useFormulaLineActions({
    setWorkspace,
    setBuilderSections,
    setResult,
    ensureRawMaterialDetail,
    markDraftReviewPending,
  });
  const {
    updateFormulaBasics,
    loadMoreCatalogMaterials,
    selectCurrentParameterView,
    clearComparisonMaterials,
  } = useFormulaBuilderLocalActions({
    catalogTotal,
    visibleParameterCodes,
    setWorkspace,
    setMaterialResultLimit,
    setComparisonMaterialIds,
    selectParameterView,
    markDraftReviewPending,
  });
  const {
    refreshJiraConnections,
    saveJiraConnection,
    testJiraConnection,
    loadJiraMetadata,
    mapJiraField,
    authorizeJiraOAuth,
  } = useJiraConnectionActions({
    workspace,
    activeJiraConnection,
    jiraConnectionForm,
    jiraMappingKey,
    headers,
    canSaveJiraConnection,
    setJiraConnections,
    setJiraConnectionForm,
    setJiraMetadata,
    setStatus,
    runAction,
    setError,
    setMessage,
  });
  const {
    parseRequirements,
    planRequirements,
    refreshAiRuns,
    reuseInfeasibilityAction,
  } = useAiAssistantActions({
    workspace,
    requirementText,
    headers,
    setRequirementParse,
    setAgentPlan,
    setAiRuns,
    setRequirementText,
    runAction,
    setError,
    setMessage,
  });
  const { createCompatibilityRule } = useCompatibilityActions({
    workspace,
    compatibilityRuleForm,
    headers,
    setCompatibilityRules,
    setCompatibilityRuleForm,
    setResult,
    runAction,
    setError,
    setMessage,
  });
  const {
    compareSavedFormulas,
    saveFormula,
    refreshFormulaLibrary,
    openFormula,
    loadCalculationHistory,
    loadFormulaReviewRequests,
  } = useSavedFormulaActions({
    workspace,
    formulas,
    formulaCompareSelection,
    rawMaterialsById,
    headers,
    isFormulaBalanced,
    hasPendingDraftReview,
    setWorkspace,
    setFormulas,
    setCalculationHistory,
    setFormulaReviewRequests,
    setFormulaReviewArtifacts,
    setResult,
    setDraftReview,
    setSavedFormulaComparison,
    setBuilderSections,
    ensureRawMaterialDetail,
    resetImportState,
    runAction,
    setError,
    setMessage,
  });
  const {
    sendCurrentFormulaToJira,
    generateJiraReviewExcel,
    downloadJiraReviewArtifact,
    sendJiraReviewToJira,
    retryJiraReviewAttachment,
    syncJiraReviewStatus,
  } = useJiraReviewActions({
    workspace,
    activeJiraConnection,
    result,
    formulaReviewRequests,
    headers,
    uploadHeaders,
    setFormulaReviewRequests,
    setFormulaReviewArtifacts,
    loadFormulaReviewRequests,
    runAction,
    setError,
    setMessage,
  });
  const {
    selectExcelImportFile,
    previewSelectedImportSheet,
    saveExcelImport,
    resolveImportRow,
    acceptImportSuggestion,
    createMaterialFromImportRow,
    createAliasFromImportRow,
  } = useExcelImportActions({
    workspace,
    importPreview,
    importFile,
    headers,
    uploadHeaders,
    setWorkspace,
    setDetailedMaterialIds,
    setResult,
    setDraftReview,
    setSavedFormulaComparison,
    setPendingFile,
    setImportPreview,
    setSelectedImportSheet,
    resolveImportRowState,
    refreshCatalog,
    refreshFormulaLibrary,
    loadCalculationHistory,
    runAction,
    setError,
    setMessage,
  });

  if (!authChecked || !session) {
    return <WorkspaceAuthGate />;
  }

  const panels = {
    settings: {
      workspace,
      workspaceName,
      sessionEmail: session.user.email,
      invitationForm,
      tenantInvitations,
      parameterForm,
      activeJiraConnection,
      jiraConnectionForm,
      jiraMetadata,
      jiraMappingKey,
      isBusy,
      canEditTenantData,
      canManageTenantUsers,
      canSaveJiraConnection,
      canTestJiraConnection,
      canLoadJiraMetadata,
      canAuthorizeJiraOAuth,
      showInvitationAdminPanel,
      onWorkspaceNameChange: setWorkspaceName,
      onCreateWorkspace: createWorkspace,
      onInvitationFormChange: setInvitationForm,
      onCreateTenantInvitation: createTenantInvitation,
      onParameterFormChange: setParameterForm,
      onCreateParameter: createParameter,
      onJiraConnectionFormChange: setJiraConnectionForm,
      onSaveJiraConnection: saveJiraConnection,
      onRefreshJiraConnections: refreshJiraConnections,
      onTestJiraConnection: testJiraConnection,
      onLoadJiraMetadata: loadJiraMetadata,
      onAuthorizeJiraOAuth: authorizeJiraOAuth,
      onJiraMappingKeyChange: setJiraMappingKey,
      onMapJiraField: mapJiraField,
    },
    rawMaterials: {
      rawMaterials: workspace.rawMaterials,
      parameter: workspace.parameter,
      materialForm,
      aliasInputs,
      canEditTenantData,
      isBusy,
      onMaterialFormChange: setMaterialForm,
      onAliasInputsChange: setAliasInputs,
      onCreateMaterial: createMaterial,
      onAddFormulaLine: addFormulaLine,
      onCreateAlias: createAlias,
    },
    compatibility: {
      rules: compatibilityRules,
      rawMaterials: workspace.rawMaterials,
      rawMaterialsById,
      form: compatibilityRuleForm,
      canEditTenantData,
      canCreateRule: canCreateCompatibilityRule,
      onFormChange: setCompatibilityRuleForm,
      onCreateRule: createCompatibilityRule,
    },
    library: {
      formulas,
      calculationHistory,
      formulaCompareSelection,
      comparisonConstraintForm,
      comparisonMaterialOptions,
      canEditTenantData,
      canCompareSavedFormulas,
      isBusy,
      savedFormulaComparison,
      comparisonComplianceSummary,
      comparisonConstraintEvaluations,
      comparisonConstraintIssueCount,
      visibleComparisonConstraintEvaluations,
      showOnlyConstraintIssues,
      onSelectFormula: selectFormulaForComparison,
      onRefreshLibrary: refreshFormulaLibrary,
      onCompareSavedFormulas: compareSavedFormulas,
      onOpenFormula: openFormula,
      onUpdateConstraint: updateComparisonConstraint,
      onShowOnlyConstraintIssuesChange: setShowOnlyConstraintIssues,
    },
    excelImport: {
      importPreview,
      importFileName,
      availableImportSheets,
      selectedImportSheet,
      rawMaterials: workspace.rawMaterials,
      canEditTenantData,
      canSelectImportSheet,
      canSaveImport,
      isBusy,
      onSelectFile: selectExcelImportFile,
      onPreviewSheet: previewSelectedImportSheet,
      onSaveImport: saveExcelImport,
      onResolveRow: resolveImportRow,
      onCreateMaterialFromRow: createMaterialFromImportRow,
      onAcceptSuggestion: acceptImportSuggestion,
      onCreateAliasFromRow: createAliasFromImportRow,
    },
    aiAssistant: {
      requirementText,
      requirementParse,
      agentPlan,
      aiRuns,
      canParseRequirements,
      canPlanRequirements,
      canEditTenantData,
      isBusy,
      onRequirementTextChange: setRequirementText,
      onParseRequirements: parseRequirements,
      onPlanRequirements: planRequirements,
      onRefreshAiRuns: refreshAiRuns,
      onReuseInfeasibilityAction: reuseInfeasibilityAction,
      onApplyOptimizerDraft: applyOptimizerDraft,
    },
    formulaBuilder: {
      totalPercentage,
      isFormulaBalanced,
      basics: {
        isOpen: builderSections.basics,
        isBusy,
        hasActiveJiraConnection: Boolean(activeJiraConnection),
        values: formulaBasicsValue,
        onToggle: toggleBuilderSection,
        onChange: updateFormulaBasics,
      },
      materials: {
        isOpen: builderSections.materials,
        catalogLoading,
        catalogTotal,
        visibleParameterSummary,
        selectedPresetHelper: selectedParameterPreset.helper,
        showOnlyPositiveParameters,
        parameterViewPreset,
        parameterCatalog,
        customParameterCodes,
        formulaMaterialQuery,
        canSearch: canSearchCatalog,
        catalogParameterConditions,
        catalogFamilyFilter,
        catalogMaterialFamilies,
        catalogPriceFilter,
        catalogPriceMin,
        catalogPriceMax,
        catalogParameterToAdd,
        visibleParameterCodeSet,
        materialResultLimit,
        materialSearchResults,
        workspaceMaterialCount: workspace.rawMaterials.length,
        formulaLines: workspace.formulaLines,
        selectedMaterialId,
        selectedMaterial,
        selectedMaterialParameters,
        comparisonMaterials,
        detailedMaterialIds,
        expandedMaterialIds,
        comparisonMaterialIds,
        visibleParameterCodes,
        isBusy,
        onToggle: toggleBuilderSection,
        onShowOnlyPositiveChange: setShowOnlyPositiveParameters,
        onSelectParameterView: selectCurrentParameterView,
        onToggleCustomParameterCode: toggleCustomParameterCode,
        onQueryChange: setFormulaMaterialQuery,
        onFamilyFilterChange: setCatalogFamilyFilter,
        onPriceFilterChange: setCatalogPriceFilter,
        onPriceMinChange: setCatalogPriceMin,
        onPriceMaxChange: setCatalogPriceMax,
        onParameterToAddChange: setCatalogParameterToAdd,
        onAddCondition: addCatalogParameterCondition,
        onUpdateCondition: updateCatalogParameterCondition,
        onRemoveCondition: removeCatalogParameterCondition,
        onLoadMoreMaterials: loadMoreCatalogMaterials,
        onResetFilters: resetCatalogFilters,
        onInspectMaterial: inspectMaterial,
        onToggleCompareMaterial: toggleCompareMaterial,
        onAddFormulaLine: addFormulaLine,
        onToggleExpandedMaterial: toggleExpandedMaterial,
        onClearComparison: clearComparisonMaterials,
      },
      composition: {
        isOpen: builderSections.formula,
        lineCount: workspace.formulaLines.length,
        totalPercentage,
        isFormulaBalanced,
        price: formulaCompositionPrice,
        priceSource: formulaCompositionPriceSource,
        draftReview,
        draftComparison,
        isBusy,
        canConfirmDraftReview,
        activeJiraConnection,
        formulaReviewRequests,
        formulaReviewArtifacts,
        canPrepareJiraReview,
        formulaLineDetails,
        visibleParameterCodes,
        showOnlyPositiveParameters,
        onToggle: toggleBuilderSection,
        onNotesChange: updateDraftReviewNotes,
        onConfirmDraftReview: confirmDraftReview,
        onSendCurrentFormulaToJira: sendCurrentFormulaToJira,
        onGenerateReviewExcel: generateJiraReviewExcel,
        onDownloadArtifact: downloadJiraReviewArtifact,
        onSendReviewToJira: sendJiraReviewToJira,
        onSyncReviewStatus: syncJiraReviewStatus,
        onRetryReviewAttachment: retryJiraReviewAttachment,
        onMoveLine: moveFormulaLine,
        onUpdateLine: updateFormulaLine,
        onDuplicateLine: duplicateFormulaLine,
        onRemoveLine: removeFormulaLine,
      },
      calculation: {
        isOpen: builderSections.calculation,
        isBackendResult: Boolean(result),
        parameterRows,
        visibleWarnings,
        selectedPresetLabel: selectedParameterPreset.label,
        visibleParameterSummary,
        showOnlyPositiveParameters,
        parameterViewPreset,
        isFormulaBalanced,
        totalPercentage,
        isBusy,
        canSaveFormula,
        onToggle: toggleBuilderSection,
        onShowOnlyPositiveChange: setShowOnlyPositiveParameters,
        onSelectParameterView: selectCurrentParameterView,
        onSaveFormula: saveFormula,
      },
    },
    results: { result },
  } satisfies WorkspaceHomePanels;

  return (
    <WorkspaceHomeView
      activeView={activeView}
      workspace={workspace}
      sessionEmail={session.user.email}
      status={status}
      message={message}
      isBusy={isBusy}
      onViewChange={setActiveView}
      onSignOut={signOut}
      panels={panels}
    />
  );
}
