from .parameter_order import PARAMETER_ORDER

FORMULA_ID_LAB_TEMPLATE_KEY = "atlantica_id_lab"
FORMULA_ID_LAB_EXCEL_TYPE = "formula_id_lab_xlsx"
FORMULA_ID_LAB_EXCEL_CONTENT_TYPE = (
    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
)

CALCULATOR_SHEET_NAME = "Calculadora"
LAB_SHEET_NAME = "Hoja Lab"
COMPOSITION_SHEET_NAME = "Composición"

CALCULATOR_HEADER_ROW = 1
CALCULATOR_FIRST_ITEM_ROW = 2
CALCULATOR_MATERIAL_COLUMN = 1
CALCULATOR_PERCENTAGE_COLUMN = 2
CALCULATOR_PRICE_COLUMN = 3
CALCULATOR_FIRST_PARAMETER_COLUMN = 4

LAB_FIRST_ITEM_ROW = 6
LAB_ORDER_COLUMN = 1
LAB_MATERIAL_COLUMN = 3
LAB_PERCENTAGE_COLUMN = 4
LAB_HALF_KG_COLUMN = 5
LAB_TWO_KG_COLUMN = 6
LAB_OBSERVATION_COLUMN = 7

COMPOSITION_PRICE_ROW = 3
COMPOSITION_FIRST_PARAMETER_ROW = 4

LEGACY_PARAMETER_ORDER = PARAMETER_ORDER
